//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwimmiePooLogParserDispatcher.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentParseLine
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public int LineNumber { get; set; }
        public string Line { get; set; }
        public Nullable<int> DroneId { get; set; }
        public string Path { get; set; }
    }
}
