//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwimmiePooLogParserDispatcher.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drone
    {
        public int DroneId { get; set; }
        public string Title { get; set; }
        public string BaseUrl { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int SortOrder { get; set; }
    }
}
